### PR TITLE
correct url redirect

### PR DESCRIPTION
**Pull request by michaelhjulskov**

### CODE REVIEW

**Comment by michaelhjulskov** [comment]
maybe without the urlencode()
up to you guys
hope it helps

**Comment by gRoussac** [comment]
Hi,

Thank your for PR but sorry please use the 'dev' brach, not the master branch.

Regards

**Comment by michaelhjulskov** [comment]
U can do Whatever u want. Now u know

Med venlig hilsen
Michael Hjulskov
Mobil 22116322
Den 18/02/2015 12.00 skrev "Gregory Roussac" <notifications@github.com>:

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution, I have just reported your change in this PR #13 

Best regards

**Pull request closed without merging**
